export const menuBarCategories = [
  "Cocktails",
  "Vins & Bières",
  "Alcools",
  "Softs & Boissons Chaudes",
];

export const menuBar = [
  {
    index: 1,
    category: "Cocktails",
    subCategory: "Les Cocktails Classiques",
    name: "Espresso Martini",
    description: "Vodka, Kahlua, espresso",
    price: 14,
  },
  {
    index: 2,
    category: "Cocktails",
    subCategory: "Les Cocktails Classiques",
    name: "Mojito",
    description: "Rhum, Menthe, citron vert, sirop de sucre, Perrier",
    price: 14,
  },
  {
    index: 3,
    category: "Cocktails",
    subCategory: "Les Cocktails Classiques",
    name: "Apérol Spritz",
    description: "Apérol, Prosecco, Perrier",
    price: 14,
  },
  {
    index: 4,
    category: "Cocktails",
    subCategory: "Les Cocktails Classiques",
    name: "Gin Tonic Concombre",
    description: "Gin, Tonic, Citron, Concombre",
    price: 14,
  },
  {
    index: 5,
    category: "Cocktails",
    subCategory: "Les Cocktails Classiques",
    name: "Negroni",
    description: "Gin, Campari, Vermouth Rouge",
    price: 14,
  },
  {
    index: 6,
    category: "Cocktails",
    subCategory: "Les Cocktails Créations",
    name: "Limonade pour Adultes",
    description: "Gin, Limoncello, Bitter orange, Cointreau, limonade, citron",
    price: 15,
  },
  {
    index: 7,
    category: "Cocktails",
    subCategory: "Les Cocktails Créations",
    name: "Hakunah Matata",
    description: "Rhum, Passion, Sirop d’érable, Ginger Beer",
    price: 15,
  },
  {
    index: 8,
    category: "Cocktails",
    subCategory: "Les Cocktails Créations",
    name: "Guilty Love",
    description: "Vodka, Liqueur de Violette, Basilic, Framboise, Pomme",
    price: 15,
  },
  {
    index: 9,
    category: "Cocktails",
    subCategory: "Les Cocktails Créations",
    name: "Pisteur (parfait en Dessert ou Digestif)",
    description: "Whisky, crème de noisette, liqueur de café, absinthe",
    price: 15,
  },
  {
    index: 10,
    category: "Cocktails",
    subCategory: "Les Sans alcool",
    name: "Virgin Mojito",
    description: "Limonade, menthe, citron vert, sucre de canne",
    price: 10,
  },
  {
    index: 11,
    category: "Cocktails",
    subCategory: "Les Sans alcool",
    name: "Limonade du Rendez Vous",
    description: "Orange, Citron, Limonade",
    price: 10,
  },
  {
    index: 12,
    category: "Cocktails",
    subCategory: "Les Sans alcool",
    name: "Green Light Détox",
    description: "Pomme, menthe, concombre, citron vert",
    price: 10,
  },
  {
    index: 13,
    category: "Cocktails",
    subCategory: "Spécialités",
    name: "Vin chaud à l’ancienne",
    price: 6,
  },
  {
    index: 14,
    category: "Cocktails",
    subCategory: "Spécialités",
    name: "Irish Coffee",
    price: 10,
  },
  {
    index: 15,
    category: "Cocktails",
    subCategory: "Spécialités",
    name: "Special Coffee",
    price: 10,
  },
  {
    index: 16,
    category: "Cocktails",
    subCategory: "Spécialités",
    name: "Grog",
    price: 10,
  },
  {
    index: 17,
    category: "Vins & Bières",
    subCategory: "Apéritifs",
    name: "Le Rendez-Vous",
    description: "Crème de Châtaigne, Prosecco",
    price: 8,
  },
  {
    index: 18,
    category: "Vins & Bières",
    subCategory: "Apéritifs",
    name: "Les Kirs",
    description: "Châtaigne, Framboise, Pêche, Mûre, Cassis",
    price: 5.5,
  },
  {
    index: 19,
    category: "Vins & Bières",
    subCategory: "Apéritifs",
    name: "Suze, Martini, Campari",
    price: 7,
  },
  {
    index: 20,
    category: "Vins & Bières",
    subCategory: "Apéritifs",
    name: "Porto rouge, Porto blanc",
    price: 7,
  },
  {
    index: 21,
    category: "Vins & Bières",
    subCategory: "Apéritifs",
    name: "Ricard",
    price: 4,
  },
  {
    index: 22,
    category: "Vins & Bières",
    subCategory: "Vins au Verre",
    name: "Demander nos vins du moment",
  },
  {
    index: 23,
    category: "Vins & Bières",
    subCategory: "La Coup de Champagne",
    name: "Brut",
    description: "12cl",
    price: 9,
  },
  {
    index: 24,
    category: "Vins & Bières",
    subCategory: "La Coup de Champagne",
    name: "Royale",
    description: "Châtaigne, Framboise, Pêche, Mûre, Cassis",
    price: 10,
  },
  {
    index: 25,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Rémy Massin",
    price: 65,
  },
  {
    index: 26,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Laurent Perrier Brut",
    price: 85,
  },
  {
    index: 27,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Laurent Perrier Rosé",
    price: 125,
  },
  {
    index: 28,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Laurent Perrier Blanc de Blanc ",
    price: 120,
  },
  {
    index: 29,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Laurent Perrier Brut Magnum",
    price: 160,
  },
  {
    index: 30,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Ruinart Brut",
    price: 90,
  },
  {
    index: 31,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Krug Grande Cuvée",
    price: 380,
  },
  {
    index: 32,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Cristal Roederer",
    description: "2013",
    price: 320,
  },
  {
    index: 33,
    category: "Vins & Bières",
    subCategory: "Champagne Bouteilles",
    name: "Dom Pérignon",
    description: "2010",
    price: 280,
  },
  {
    index: 34,
    category: "Vins & Bières",
    subCategory: "Bières Pression",
    name: "Kro 1947",
    price25: 4.5,
    price50: 9,
  },
  {
    index: 35,
    category: "Vins & Bières",
    subCategory: "Bières Pression",
    name: "Grimbergen Blonde",
    price25: 5.5,
    price50: 9.5,
  },
  {
    index: 36,
    category: "Vins & Bières",
    subCategory: "Bières Pression",
    name: "1664 Blanche",
    price25: 5.5,
    price50: 9.5,
  },
  {
    index: 37,
    category: "Vins & Bières",
    subCategory: "Bières Bouteilles",
    name: "Corona, Desperados",
    price: 8,
  },
  {
    index: 38,
    category: "Vins & Bières",
    subCategory: "Bières Bouteilles",
    name: "Duvel, Chouffe, Vedette IPA",
    price: 8,
  },
  {
    index: 39,
    category: "Vins & Bières",
    subCategory: "Bières Bouteilles",
    name: "Magners CidreBar ",
    price: 8,
  },
  {
    index: 40,
    category: "Alcools",
    subCategory: "Whiskys",
    name: "Clan Campbell, Jameson",
    price: 8,
  },
  {
    index: 41,
    category: "Alcools",
    subCategory: "Whiskys",
    name: "Jack Daniels",
    price: 9,
  },
  {
    index: 42,
    category: "Alcools",
    subCategory: "Whiskys",
    name: "Chivas",
    description: "12 ans",
    price: 11,
  },
  {
    index: 43,
    category: "Alcools",
    subCategory: "Whiskys",
    name: "Johnny Walker Black Label ",
    description: "12 ans",
    price: 11,
  },
  {
    index: 44,
    category: "Alcools",
    subCategory: "Whiskys",
    name: "Glenmorangie",
    description: "10 ans",
    price: 12,
  },
  {
    index: 45,
    category: "Alcools",
    subCategory: "Whiskys",
    name: "Four Roses",
    price: 9,
  },
  {
    index: 46,
    category: "Alcools",
    subCategory: "Digestifs",
    name: "Cognac VS",
    description: "Courvoisier",
    price: 1,
  },
  {
    index: 47,
    category: "Alcools",
    subCategory: "Digestifs",
    name: "Cognac VSOP",
    description: "Rémy Martin",
    price: 12.5,
  },
  {
    index: 48,
    category: "Alcools",
    subCategory: "Digestifs",
    name: "Fine Calvados",
    description: "Père Magloire",
    price: 9,
  },
  {
    index: 49,
    category: "Alcools",
    subCategory: "Digestifs",
    name: "Marc de Savoie",
    price: 9,
  },
  {
    index: 50,
    category: "Alcools",
    subCategory: "Digestifs",
    name: "Framboise, Mirabelle",
    price: 9,
  },
  {
    index: 51,
    category: "Alcools",
    subCategory: "Digestifs",
    name: "Poire Williams",
    price: 9,
  },
  {
    index: 52,
    category: "Alcools",
    subCategory: "Digestifs",
    name: "Grappa",
    price: 9,
  },
  {
    index: 53,
    category: "Alcools",
    subCategory: "Rhums Vieux",
    name: "Diplomatico",
    description: "Reserva Exclusiva",
    price: 11,
  },
  {
    index: 54,
    category: "Alcools",
    subCategory: "Rhums Vieux",
    name: "Don Papa",
    description: "Philippines",
    price: 11,
  },
  {
    index: 55,
    category: "Alcools",
    subCategory: "Rhums Vieux",
    name: "Kraken",
    description: "US Spiced",
    price: 11,
  },
  {
    index: 56,
    category: "Alcools",
    subCategory: "Rhums Vieux",
    name: "Zacapa",
    description: "23 ans Guatemala",
    price: 15,
  },
  {
    index: 57,
    category: "Alcools",
    subCategory: "Rhums Vieux",
    name: "Matusalem",
    description: "15 ans Cuba",
    price: 12,
  },
  {
    index: 58,
    category: "Alcools",
    subCategory: "Rhums Vieux",
    name: "Angostura 1919",
    price: 15,
  },
  {
    index: 59,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Vodka, Gin, Tequila",
    price: 8,
  },
  {
    index: 60,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Vodka Greygoose",
    price: 11,
  },
  {
    index: 61,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Gin Bombay Sapphire",
    price: 10,
  },
  {
    index: 62,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Gin Hendrick's",
    price: 10,
  },
  {
    index: 63,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Gin Tanqueray",
    price: 10,
  },
  {
    index: 64,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Mix Drink",
    price: 8.5,
  },
  {
    index: 65,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Mix Drink Supérieur",
    price: 11.5,
  },
  {
    index: 66,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Shooter",
    price: 5,
  },
  {
    index: 67,
    category: "Alcools",
    subCategory: "Autres Alcools",
    name: "Shooter Supérieur",
    price: 6,
  },
  {
    index: 68,
    category: "Alcools",
    subCategory: "Liquers",
    name: "Génépi",
    price: 7,
  },
  {
    index: 69,
    category: "Alcools",
    subCategory: "Liquers",
    name: "Limoncelle",
    price: 7,
  },
  {
    index: 70,
    category: "Alcools",
    subCategory: "Liquers",
    name: "Chartreuse Jaune",
    price: 9,
  },
  {
    index: 71,
    category: "Alcools",
    subCategory: "Liquers",
    name: "Chartreuse Verte, Get27, Get31",
    price: 9,
  },
  {
    index: 72,
    category: "Alcools",
    subCategory: "Liquers",
    name: "Cointreau, Grand Marnier",
    price: 8,
  },
  {
    index: 73,
    category: "Alcools",
    subCategory: "Liquers",
    name: "Jagermeister, Sambucca",
    price: 7,
  },
  {
    index: 74,
    category: "Alcools",
    subCategory: "Liquers",
    name: "Amaretto, Baileys",
    price: 8,
  },
  {
    index: 75,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Coca-Cola",
    description: "33 cl",
    price: 5,
  },
  {
    index: 76,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Coca-Cola Zéro",
    description: "33 cl",
    price: 5,
  },
  {
    index: 77,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Coca-Cola Cherry",
    description: "33 cl",
    price: 5,
  },
  {
    index: 78,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Sprite, Fanta Orange",
    description: "33 cl",
    price: 5,
  },
  {
    index: 79,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Orangina",
    description: "33 cl",
    price: 5,
  },
  {
    index: 80,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Fuze Tea, Tropico",
    description: "25cl",
    price: 4.5,
  },
  {
    index: 81,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Monster",
    price: 6,
  },
  {
    index: 82,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Orange, Citron pressé",
    price: 6,
  },
  {
    index: 83,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Pamplemousse",
    price: 7,
  },
  {
    index: 84,
    category: "Softs & Boissons Chaudes",
    subCategory: "Softs",
    name: "Jus de Fruit",
    description: "20 cl - Orange, Abricot, Pomme, Ananas, Tomate",
    price: 4.5,
  },
  {
    index: 85,
    category: "Softs & Boissons Chaudes",
    subCategory: "Eaux",
    name: "Evian",
    description: "Litre",
    price: 7,
  },
  {
    index: 86,
    category: "Softs & Boissons Chaudes",
    subCategory: "Eaux",
    name: "Badoit",
    description: "Litre",
    price: 7,
  },
  {
    index: 87,
    category: "Softs & Boissons Chaudes",
    subCategory: "Eaux",
    name: "Badoit Rouge",
    description: "33 cl",
    price: 5,
  },
  {
    index: 88,
    category: "Softs & Boissons Chaudes",
    subCategory: "Eaux",
    name: "1/4 Vittel",
    description: "25cl",
    price: 4,
  },
  {
    index: 89,
    category: "Softs & Boissons Chaudes",
    subCategory: "Cafés",
    name: "Expresso, Café Allongé",
    price: 2.5,
  },
  {
    index: 90,
    category: "Softs & Boissons Chaudes",
    subCategory: "Cafés",
    name: "Double Expresso",
    price: 5,
  },
  {
    index: 91,
    category: "Softs & Boissons Chaudes",
    subCategory: "Cafés",
    name: "Grand Crème",
    price: 5,
  },
  {
    index: 92,
    category: "Softs & Boissons Chaudes",
    subCategory: "Cafés",
    name: "Cappuccino",
    price: 5.5,
  },
  {
    index: 93,
    category: "Softs & Boissons Chaudes",
    subCategory: "Cafés",
    name: "Café Viennois",
    price: 5.5,
  },
  {
    index: 94,
    category: "Softs & Boissons Chaudes",
    subCategory: "Cafés",
    name: "Double Expresso Alcool",
    price: 7,
  },
  {
    index: 95,
    category: "Softs & Boissons Chaudes",
    subCategory: "Chocolats",
    name: "Chocolat Chaud",
    price: 5,
  },
  {
    index: 96,
    category: "Softs & Boissons Chaudes",
    subCategory: "Chocolats",
    name: "Chocolat Viennois",
    price: 5.5,
  },
  {
    index: 97,
    category: "Softs & Boissons Chaudes",
    subCategory: "Chocolats",
    name: "Chocolat Alcool",
    price: 7,
  },
  {
    index: 98,
    category: "Softs & Boissons Chaudes",
    subCategory: "Chocolats",
    name: "Chocolat Alcool Viennois",
    price: 7.5,
  },
  {
    index: 99,
    category: "Softs & Boissons Chaudes",
    subCategory: "Chocolats",
    name: "Lait Froid, Chaud",
    price: 3,
  },

  {
    index: 100,
    category: "Softs & Boissons Chaudes",
    subCategory: "Thés",
    name: "Thé",
    description:
      "Noir, Vert, Vert menthe, Earl Grey, Christmas tea, Russe Noir Génépi",
    price: 5,
  },
  {
    index: 101,
    category: "Softs & Boissons Chaudes",
    subCategory: "Thés",
    name: "Thé Alcool",
    price: 7,
  },
  {
    index: 102,
    category: "Softs & Boissons Chaudes",
    subCategory: "Thés",
    name: "Infusions",
    description: "Alpages, Verveine, Tilleul",
    price: 5,
  },
];
