export const menuCategories = [
  "Nos Cicchettis à Partager",
  "Entrées",
  "La Pasta",
  "La Viande",
  "Le Poisson",
  "Les Specialités Savoyardes",
  "Les Pizzas",
  "Menu enfant",
  "Les Desserts",
];

export const menu = [
  {
    index: 1,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Arancini x4",
    frenchDescription:
      "Boulettes de riz safranées fourrées à la scamorza, petits pois, viande",
    englishDescription:
      "Deep fried saffron rice balls stuffed with scarmorza, peas and meat",
    price: 12,
    perPerson: false,
    eveningOnly: true,
  },
  {
    index: 2,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Arancini x4",
    frenchDescription: "Assortiment de charcuterie et de fromages italiens ",
    englishDescription:
      " Assortment of cured meat and Italian cheeses served with focaccia bread",
    price: 25,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 3,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Polpette di melanzane x 4",
    frenchDescription:
      "Bouchées d’aubergine parfumées à l’ail et au basilic accompagnées de sa sauce tomate",
    englishDescription:
      "Aubergine nibbles flavoured with garlic and basil and its tomato sauce",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 4,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Montanare x 4",
    frenchDescription: "Mini pizzas façon beignet, tomate, parmesan, basilic",
    englishDescription: "Fried mini pizza with tomato, parmesan and basil",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 5,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Crochette di patate",
    frenchDescription: "Croquettes de pdt farcies au jambon et fromage",
    englishDescription: "Potato croquettes stuffed with ham and cheese",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 6,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Roulés de pizza au jambon",
    frenchDescription: "Jambon, burratina, champignons, roquette",
    englishDescription: "Ham, burrattina, mushrooms, rocket",
    price: 13,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 7,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Velouté de champignons",
    frenchDescription:
      "et son sauté de champignons de Paris, burrata, crème de truffe",
    englishDescription:
      "Cream of Paris mushroom, burrata cheese, truffle cream",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 8,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Millefeuille d’aubergines",
    frenchDescription: "Aubergines, tomates, Provola fûmée",
    englishDescription: "Aubergines, tomato and smoked Provola",
    price: 19,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 9,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Carpaccio de boeuf	",
    englishDescription: "Beef Carpaccio",
    price: 20,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 10,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Salade Caponata",
    frenchDescription:
      "Tomates cerise, anchois, roquette, buratta, oignons, olives et sa focaccia pesto",
    englishDescription:
      "Cherry tomato, anchovy, rocket, onions, olives and its pesto focaccia",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 11,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Salade italienne",
    frenchDescription:
      "Tomates cerise, roquette, mozzarella, jambon cru, légumes marinés, pignons de pin, pesto",
    englishDescription:
      "Cherry tomato, rocket, mozzarella, cured ham, marinated vegetables, pine nuts, pesto",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 12,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Salade de poulet",
    frenchDescription:
      "Salade verte, poulet pané, parmesan, tomates cerise, oignons, croûtons",
    englishDescription:
      "Salad, breaded chicken, parmesan, cherry tomato, onions, croutons",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 13,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Pennette allo scarpariello",
    frenchDescription: "Sauce tomate cerise, parmesan, piment",
    englishDescription: "Spicy cherry tomato sauce, parmesan",
    price: 19,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 14,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Linguini alle vongole",
    frenchDescription: "Linguine aux palourdes",
    englishDescription: "Linguine with clams",
    price: 25,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 15,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Paccheri ai gamberi e burrata",
    frenchDescription: "Gambas, burrata, tomates cerise",
    englishDescription: "Gambas, burrata, cherry tomato",
    price: 26,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 16,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Spaghetti alla carbonara vera",
    frenchDescription: "Lardons, œuf, parmesan",
    englishDescription: "Bacon, egg, parmesan",
    price: 19,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 17,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Gnocchi di ricotta alla siciliana ",
    frenchDescription: "Aubergine, tomate, mozzarella, parmesan râpé, pesto",
    englishDescription: " Aubergine, tomato, mozzarella, parmesan, pesto",
    price: 24,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 18,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Calamarata ai frutti di mare",
    frenchDescription: "Tomate, calamars, gambas, palourdes, moules",
    englishDescription: "Tomato, squids, gambas, clams, mussels",
    price: 27,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 19,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Spaghetti alla Nerano",
    frenchDescription: "Courgettes et Pecorino",
    englishDescription: "Courgettes and Pecorino cheese",
    price: 19,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 20,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "La padella de risotto à partager - 2 pers min",
    frenchDescription: "Risotto fruits de mer - 15 mn d’attente",
    englishDescription: "SeafoodRisotto to share - 15 mn of delay ",
    price: 27,
    perPerson: true,
    eveningOnly: true,
  },

  {
    index: 21,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Burger Savoyard",
    frenchDescription:
      "Raclette, steak haché, bacon, tomate, salade, oignons+ frites",
    englishDescription:
      "Raclette, minced beef, bacon, tomato, salad, onions +fries",
    price: 24,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 22,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Tartare italien aux artichauts",
    frenchDescription:
      "Pesto, câpres, tomates confites, crème de balsamique, artichauts confits avec frites",
    englishDescription:
      " Beef Tartar, pesto, capers, tomato confit, balsamic cream, and preserved artichokes and fries",
    price: 27,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 23,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Polpette della nonna	",
    frenchDescription:
      "Boulettes de viande de bœuf en sauce tomate avec spaghettis",
    englishDescription: " Beef meatballs in tomato sauce with spaghetti",
    price: 21,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 24,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Escalope de veau à la milanese",
    frenchDescription:
      "Escalope panée accompagnée de spaghettis à la crème de parmesan",
    englishDescription:
      "Breaded escalope of veal with spaghetti and parmesan cream",
    price: 27,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 25,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Tagliata de bœuf",
    frenchDescription:
      "Pavé de bœuf tranché, roquette, tomates cerise, parmesan avec frites",
    englishDescription:
      "Thinly-sliced beef, rocket, cherry tomatoes, parmesan with fries",
    price: 29,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 26,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "½ Coquelet rôti",
    frenchDescription: "½ Coquelet rôti et sa purée parfumée à la truffe",
    englishDescription:
      "Roasted ½ cockerel with its purée flavoured with cream truffle",
    price: 26,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 27,
    categoryFrench: "Le Poisson",
    categoryEnglish: "Fish",
    name: "Cassolette de moules",
    frenchDescription: "Moules à la tomate, frites",
    englishDescription: "Mussels with tomato, fries",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 28,
    categoryFrench: "Le Poisson",
    categoryEnglish: "Fish",
    name: "Aïoli",
    frenchDescription:
      "Cabillaud accompagné de ses légumes, bulots et mayonnaise à l’ail",
    englishDescription:
      "Codfish with vegetables, whelks and garlic mayonnaise ",
    price: 27,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 29,
    categoryFrench: "Les Specialités Savoyardes",
    name: "Tartiflette au Reblochon AOP, salade",
    frenchDescription: "Savoyarde tartiflette, salade",
    englishDescription: "Savoyarde tartiflette served with salad",
    price: 25,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 30,
    categoryFrench: "Les Specialités Savoyardes",
    name: "Raclette au lait cru de Savoie  - 2 pers min",
    frenchDescription: "Servie avec pomme de terre et charcuterie",
    englishDescription:
      "Raclette cheese grilled at the table, served with potatoes and cured meats",
    price: 35,
    perPerson: true,
    eveningOnly: true,
  },
  {
    index: 31,
    categoryFrench: "Les Specialités Savoyardes",
    name: "Pierrade	- 2 pers min",
    frenchDescription: "Bœuf, poulet, veau accompagné de crudités et frites",
    englishDescription:
      "Beef, chicken and veal, cooked at the table on a hot stone with raw vegetables and fries",
    price: 35,
    perPerson: true,
    eveningOnly: false,
  },

  {
    index: 32,
    categoryFrench: "Les Pizzas",
    name: "Focaccia",
    frenchDescription: "Roquette, jambon cru, burratina, tomates cerise, pesto",
    englishDescription:
      "Rocket salad, cured ham, burratina, cherry tomato, pesto",
    price: 20,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 33,
    categoryFrench: "Les Pizzas",
    name: "Giuletta	(chausson / in purse)",
    frenchDescription: "Roquette, mozzarella buffala, jambon cru, parmesan",
    englishDescription: " Rocket, buffalo mozzarella, cured ham, parmesan",
    price: 20,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 34,
    categoryFrench: "Les Pizzas",
    name: "Margarita",
    frenchDescription: "Tomate, mozzarella",
    englishDescription: "Tomato, mozzarella",
    price: 14,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 35,
    categoryFrench: "Les Pizzas",
    name: "Amalfi	(chausson / in purse)",
    frenchDescription: "Tomate, ricotta, chorizo",
    englishDescription: "Tomato, ricotta, chorizo",
    price: 16.5,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 36,
    categoryFrench: "Les Pizzas",
    name: "Napolitaine",
    frenchDescription: "Tomate, mozzarella, anchois, basilic, olives",
    englishDescription: "Tomato, mozzarella, anchovy, basil, olives",
    price: 16.5,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 37,
    categoryFrench: "Les Pizzas",
    name: "Romana",
    frenchDescription: "Tomate, jambon blanc, mozzarella, champignons de Paris",
    englishDescription: "Tomato, ham, mozzarella, button mushrooms",
    price: 17.5,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 38,
    categoryFrench: "Les Pizzas",
    name: "Sicilienne",
    frenchDescription: "Tomate, mozzarella, chorizo, olives, basilic",
    englishDescription: "Tomato, mozzarella, chorizo, olives, basil",
    price: 17.5,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 39,
    categoryFrench: "Les Pizzas",
    name: "Végétarienne",
    frenchDescription:
      "Tomate, fromage, aubergine, courgette, poivrons, roquette, olives",
    englishDescription:
      "Tomato, cheese, aubergine, courgette, bell peppers, roquette, olives",
    price: 17.5,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 40,
    categoryFrench: "Les Pizzas",
    name: "Calzone",
    frenchDescription: "Tomate, mozzarella, jambon, champignons, crème, oeuf",
    englishDescription: "Tomato, mozzarella, ham, mushrooms, cream, egg",
    price: 18,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 41,
    categoryFrench: "Les Pizzas",
    name: "3 fromages",
    frenchDescription:
      "Crème, mozzarella, Gorgonzola, chèvre, olives, basilic,",
    englishDescription:
      " Cream, mozzarella, Gorgonzola, goat‘s cheese, olives, basil",
    price: 18.5,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 42,
    categoryFrench: "Les Pizzas",
    name: "Savoyarde",
    frenchDescription: "Crème, Reblochon, pomme de terre, oignons, lardons",
    englishDescription: "Cream, Reblochon cheese, potato, onion, bacon",
    price: 18.5,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 43,
    categoryFrench: "Les Pizzas",
    name: "Chèvre Miel",
    frenchDescription: "Crème, mozzarella, fromage de chèvre, miel, noix",
    englishDescription: "Cream, Mozzarella, goat’s cheese, honey, walnuts",
    price: 18.5,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 43,
    categoryFrench: "Menu enfant",
    categoryEnglish: "for the kids",
    frenchDescription: "Filet de poulet pané ou spaghettis carbonara + dessert",
    englishDescription:
      "Breaded chicken fillet or spaghetti carbonara + dessert",
    price: 14,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 45,
    categoryFrench: "Les Desserts",
    name: "Sélection de fromages",
    englishDescription: "Cheese platter",
    price: 13,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 46,
    categoryFrench: "Les Desserts",
    name: "Tiramisù",
    englishDescription: "Sponge fingers, mascarpone, coffee, marsala",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 47,
    categoryFrench: "Les Desserts",
    name: "Tartare de fruits",
    englishDescription: "Fruit tartare",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 48,
    categoryFrench: "Les Desserts",
    name: "Le Gâteau Mont Blanc",
    englishDescription: "Creamy chestnut cake",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 49,
    categoryFrench: "Les Desserts",
    name: "Macaron à la rose et chocolat blanc",
    englishDescription: " Rose and white chocolate macaron",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 50,
    categoryFrench: "Les Desserts",
    name: "Café gourmand",
    englishDescription: "Miniature dessert and coffee",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 51,
    categoryFrench: "Les Desserts",
    name: "Cheese cake mangue et son coulis passion",
    englishDescription: "Mango cheese cake with its passion fruit sauce",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 52,
    categoryFrench: "Les Desserts",
    name: "Le chocolat dans tous ses états",
    englishDescription: "All chocolate",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 53,
    categoryFrench: "Les Desserts",
    name: "Tarte citron déstructurée",
    englishDescription: "Crumbled lemon pie",
    price: 12,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 54,
    categoryFrench: "Les Desserts",
    name: "Colonel au limoncello",
    frenchDescription: "Sorbet citron et limoncello",
    englishDescription: "Lemon sorbet with limoncello",
    price: 11,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 55,
    categoryFrench: "Les Desserts",
    name: "Affogato Baileys",
    frenchDescription:
      "Café expresso, glace vanille, crème de Baileys, caramel",
    englishDescription: "Coffee, vanilla ice cream, Baileys, caramel",
    price: 11,
    perPerson: false,
    eveningOnly: false,
  },
];
