export const menuCategories = [
  "Nos Cicchettis à Partager",
  "Entrées",
  "La Pasta",
  "La Viande",
  // "Le Poisson",
  "Les Specialités Savoyardes",
  "Les Pizzas",
  "Menu enfant",
  "Les Desserts",
];

export const menu = [
  {
    index: 1,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Polpette di melanzane x 4",
    frenchDescription:
      "Bouchées d’aubergine parfumées à l’ail et au basilic accompagnées de sa sauce tomate",
    englishDescription:
      "Aubergine nibbles flavoured with garlic and basil and its tomato sauce",
    price: 15,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 2,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Arancini x5",
    frenchDescription:
      "Boulettes de riz safranées fourrées à la scamorza, petits pois, viande",
    englishDescription:
      "Deep fried saffron rice balls stuffed with scarmorza, peas and meat",
    price: 15,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 3,
    categoryFrench: "Nos Cicchettis à Partager",
    categoryEnglish: "Sharing Platters",
    name: "Roulés de pizza au jambon",
    frenchDescription: "Jambon, burratina, champignons, roquette",
    englishDescription: "Ham, burrattina, mushrooms, rocket",
    price: 17,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 4,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "La burrata",
    frenchDescription: "Burrata, jambon cru, olives vertes",

    englishDescription: "Burrata, cured ham, green olives",
    price: 27,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 5,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Carpaccio de boeuf	",
    englishDescription: "Beef Carpaccio",
    price: 25,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 6,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Salade italienne",
    frenchDescription:
      "Tomates cerise, roquette, burrata, légumes marinés, pignons de pin, pesto",
    englishDescription:
      "Cherry tomatoes, rocket, mozzarella, marinated vegetables, pine nuts, pesto",
    price: 26,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 7,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Salade de poulet della casa ",
    frenchDescription:
      "Salade verte, poulet pané, parmesan, tomates cerise, oignons, croûtons",
    englishDescription:
      "Salad, breaded chicken, parmigiano, cherry tomatoes, onions, croutons",
    price: 26,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 8,
    categoryFrench: "Entrées",
    categoryEnglish: "Starters",
    name: "Montanare x 3",
    frenchDescription: "Mini pizzas façon beignet aux 3 saveurs",
    englishDescription: "Fried mini pizza with 3 differents flavours",
    price: 17,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 9,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Penne alla puttanesca",
    frenchDescription: "Tomates cerise, olives",
    englishDescription: "Cherry tomatoes, olives",
    price: 21,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 10,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Spaghetti alla carbonara vera",
    frenchDescription: "Lardons, œuf, parmesan",
    englishDescription: "Bacon, egg, parmesan",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 11,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Rigattoni alla bolognese",
    frenchDescription: "Sauce bolognaise",
    englishDescription: "Bolognese sauce",
    price: 22,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 12,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Paccheri gorgonzola e pera",
    frenchDescription: "Crème de gorgonzola, poire et noix",
    englishDescription: "Gorgonzola cream, pear and walnuts",
    price: 31,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 13,
    categoryFrench: "La Pasta",
    categoryEnglish: "La Pasta",
    name: "Tortellini alla boscaiola",
    frenchDescription: "Crème, jambon cuit, petits pois, champignons",
    englishDescription: "Cream, ham, peas, mushrooms",
    price: 27,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 14,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Filet de bœuf",
    englishDescription: "Grilled beef fillet",
    price: 43,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 15,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Burger Savoyard (disponible en végétarienne - also available in vegetarian) ",
    frenchDescription:
      "Raclette, steak haché, bacon, tomate, salade, oignons + frites",
    englishDescription:
      "Raclette, minced beef, bacon, tomato, salad, onions + fries",
    price: 29,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 16,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Tartare italien aux artichauts",
    frenchDescription:
      "Pesto, câpres, tomates confites, crème de balsamique, artichauts confits avec frites",
    englishDescription:
      " Beef Tartar, pesto, capers, tomato confit, balsamic cream, and preserved artichokes and fries",
    price: 33,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 17,
    categoryFrench: "La Viande",
    categoryEnglish: "Meat",
    name: "Escalope de veau à la milanese",
    frenchDescription:
      "Escalope panée accompagnée de spaghettis à la crème de parmesan",
    englishDescription:
      "Breaded escalope of veal with spaghetti and parmesan cream",
    price: 34,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 19,
    categoryFrench: "Le Poisson",
    categoryEnglish: "Fish",
    name: "Cassolette de moules",
    frenchDescription: "Moules à la crème, frites",
    englishDescription: "Mussels with crème, fries",
    price: 27,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 20,
    categoryFrench: "Les Specialités Savoyardes",
    name: "Tartiflette au Reblochon AOP, salade",
    frenchDescription: "Savoyarde tartiflette, salade",
    englishDescription: "Savoyarde tartiflette served with salad",
    price: 31,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 21,
    categoryFrench: "Menu enfant",
    categoryEnglish: "for the kids",
    frenchDescription: "Filet de poulet pané ou ou mini carbonara  + dessert",
    englishDescription: "Breaded chicken fillet or small carbonara  + dessert",
    price: 18,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 22,
    categoryFrench: "Les Pizzas",
    name: "Focaccia",
    frenchDescription: "Roquette, jambon cru, burratina, tomates cerise, pesto",
    englishDescription:
      "Rocket salad, cured ham, burratina, cherry tomato, pesto",
    price: 25,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 23,
    categoryFrench: "Les Pizzas",
    name: "Giuletta	(chausson / in purse)",
    frenchDescription: "Roquette, mozzarella buffala, jambon cru, parmesan",
    englishDescription: " Rocket, buffalo mozzarella, cured ham, parmesan",
    price: 25,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 24,
    categoryFrench: "Les Pizzas",
    name: "Margarita",
    frenchDescription: "Tomate, mozzarella",
    englishDescription: "Tomato, mozzarella",
    price: 19,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 25,
    categoryFrench: "Les Pizzas",
    name: "Bronte",
    frenchDescription: "Mozzarella, Mortadelle, crème de pistache, pistache",
    englishDescription: "Mozzarella, Mortadella, pistachio cream",
    price: 25,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 26,
    categoryFrench: "Les Pizzas",
    name: "Napolitaine",
    frenchDescription: "Tomate, mozzarella, anchois, basilic, olives",
    englishDescription: "Tomato, mozzarella, anchovy, basil, olives",
    price: 21,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 27,
    categoryFrench: "Les Pizzas",
    name: "Romana",
    frenchDescription: "Tomate, jambon blanc, mozzarella, champignons de Paris",
    englishDescription: "Tomato, ham, mozzarella, button mushrooms",
    price: 21,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 28,
    categoryFrench: "Les Pizzas",
    name: "Sicilienne",
    frenchDescription: "Tomate, mozzarella, chorizo, olives, basilic",
    englishDescription: "Tomato, mozzarella, chorizo, olives, basil",
    price: 21,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 29,
    categoryFrench: "Les Pizzas",
    name: "Végétarienne",
    frenchDescription:
      "Tomate, fromage, aubergine, courgette, poivrons, roquette, olives",
    englishDescription:
      "Tomato, cheese, aubergine, courgette, bell peppers, roquette, olives",
    price: 21,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 30,
    categoryFrench: "Les Pizzas",
    name: "Calzone",
    frenchDescription: "Tomate, mozzarella, jambon, champignons, crème, oeuf",
    englishDescription: "Tomato, mozzarella, ham, mushrooms, cream, egg",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 31,
    categoryFrench: "Les Pizzas",
    name: "3 fromages",
    frenchDescription:
      "Crème, mozzarella, Gorgonzola, chèvre, olives, basilic,",
    englishDescription:
      " Cream, mozzarella, Gorgonzola, goat‘s cheese, olives, basil",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 32,
    categoryFrench: "Les Pizzas",
    name: "Savoyarde",
    frenchDescription: "Crème, Reblochon, pomme de terre, oignons, lardons",
    englishDescription: "Cream, Reblochon cheese, potato, onion, bacon",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 33,
    categoryFrench: "Les Pizzas",
    name: "Chèvre Miel",
    frenchDescription: "Crème, mozzarella, fromage de chèvre, miel, noix",
    englishDescription: "Cream, Mozzarella, goat’s cheese, honey, walnuts",
    price: 23,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 34,
    categoryFrench: "Les Pizzas",
    name: "Tartufo",
    frenchDescription:
      "Crème, truffe,mozzarella,burrata, roquette, copeaux parmesan",
    englishDescription:
      "Cream, truffle, mozzarella, rocket, parmigiano shavings",
    price: 38,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 35,
    categoryFrench: "Les Desserts",
    name: "Notre Carte des desserts évolue au fil de l’inspiration d'Alexandre",
    englishDescription:
      "Our dessert menu evolves according to Clémentine’s inspiration",
    price: 14,
    perPerson: false,
    eveningOnly: false,
  },

  {
    index: 36,
    categoryFrench: "Les Desserts",
    name: "Sélection de fromages",
    englishDescription: "Cheese platter",
    price: 16,
    perPerson: false,
    eveningOnly: false,
  },

  // {
  //   index: 44,
  //   categoryFrench: "Les Desserts",
  //   name: "Paris Brest",
  //   englishDescription: "Paris Brest",
  //   price: 13,
  //   perPerson: false,
  //   eveningOnly: false,
  // },
  // {
  //   index: 45,
  //   categoryFrench: "Les Desserts",
  //   name: "Tiramisù",
  //   englishDescription: "Sponge fingers, mascarpone, coffee, marsala",
  //   price: 13,
  //   perPerson: false,
  //   eveningOnly: false,
  // },

  // {
  //   index: 46,
  //   categoryFrench: "Les Desserts",
  //   name: "Croquant chocolat",
  //   englishDescription: "Chocolate croquant",
  //   price: 13,
  //   perPerson: false,
  //   eveningOnly: false,
  // },
  // {
  //   index: 47,
  //   categoryFrench: "Les Desserts",
  //   name: "Tartelette citron",
  //   englishDescription: "Lemon tartlet",
  //   price: 13,
  //   perPerson: false,
  //   eveningOnly: false,
  // },
  // {
  //   index: 48,
  //   categoryFrench: "Les Desserts",
  //   name: "Café gourmand",
  //   englishDescription: "Miniature dessert and coffee",
  //   price: 13,
  //   perPerson: false,
  //   eveningOnly: false,
  // },

  {
    index: 37,
    categoryFrench: "Les Desserts",
    name: "Colonel au limoncello",
    frenchDescription: "Sorbet citron et limoncello",
    englishDescription: "Lemon sorbet with limoncello",
    price: 14,
    perPerson: false,
    eveningOnly: false,
  },
  {
    index: 38,
    categoryFrench: "Les Desserts",
    name: "Affogato Baileys",
    frenchDescription:
      "Café expresso, glace vanille, crème de Baileys, caramel",
    englishDescription: "Coffee, vanilla ice cream, Baileys, caramel",
    price: 14,
    perPerson: false,
    eveningOnly: false,
  },
];
